### ISSUE TITLE
Feature request: kill the older tab if possible

### ISSUE THREAD

**Issue by kimsterv** [jasonpolites/tabsweeper#5]
If I open a duped tab it's usually because I don't know the other tab is open. Suggest killing the older tab instead of the one that was just opened.

**Comment by jasonpolites** [comment]
This is already the behavior if the newer tab is the one you're currently viewing. If the older tab is the one you're viewing, then you don't want that closed. If you're viewing neither, then what's the advantage of closing the older one? Are you thinking the content in the newer tab might be more recent?

**Comment by jasonpolites** [comment]
(also if you use the bug link in the options dialog it will send the version and patch number you are running)

**Comment by kimsterv** [comment]
> This is already the behavior if the newer tab is the one you're currently viewing. 

This isn't the behavior I just experienced. I'll see if it happens again.

**Comment by jasonpolites** [comment]
This seems to do what I would have expected (video)
https://github.com/jasonpolites/tabsweeper/assets/764528/2b8b0059-4522-47a2-bee4-837a401efa41

**Comment by jasonpolites** [comment]
Closing this. I think there _might_ be a bug somewhere, but I don't even recall what it might be, let alone repro it.

The original request to close the "oldest" tab seems to be an arbitrary choice, and in-fact I would suggest the opposite is more often the case. An old tab is arguably more likely to have state that you'd prefer not to lose (e.g. maybe you half filled-out a form, or half finished a comment in a doc).

Also it's a pain to implement and I'm lazy

**Comment by kimsterv** [comment]
I think you already fixed it.
